<?php

namespace Database\Seeders;

use App\Models\ActivityOffer;
use Illuminate\Database\Seeder;

class ActivityOfferSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['title' => 'Quad dans la Palmeraie de Marrakech', 'slug' => 'quad-palmeraie-marrakech', 'country' => 'Maroc', 'city' => 'Marrakech', 'category' => 'Aventure', 'duration_label' => '2 heures', 'badge' => 'À la une', 'short_description' => 'Expérience quad dans la Palmeraie avec encadrement local et assistance Ajinsafro.', 'includes' => ['Guide', 'Casque', 'Assistance Ajinsafro', 'Transport optionnel'], 'image_url' => 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&w=1200&q=80', 'price_from' => 250, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => true, 'is_active' => true, 'sort_order' => 1],
            ['title' => 'Excursion bateau à Dakhla', 'slug' => 'excursion-bateau-dakhla', 'country' => 'Maroc', 'city' => 'Dakhla', 'category' => 'Mer & bateau', 'duration_label' => 'Demi-journée', 'badge' => 'À la une', 'short_description' => 'Sortie en bateau à Dakhla pour découvrir la lagune et ses paysages naturels.', 'includes' => ['Bateau', 'Guide', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', 'price_from' => 400, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => true, 'is_active' => true, 'sort_order' => 2],
            ['title' => 'Tour culturel à Istanbul', 'slug' => 'tour-culturel-istanbul', 'country' => 'Turquie', 'city' => 'Istanbul', 'category' => 'Culture', 'duration_label' => 'Journée complète', 'badge' => 'À la une', 'short_description' => 'Visite culturelle des sites emblématiques d’Istanbul avec guide local.', 'includes' => ['Guide local', 'Assistance Ajinsafro', 'Billets optionnels'], 'image_url' => 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=1200&q=80', 'price_from' => 550, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => true, 'is_active' => true, 'sort_order' => 3],
            ['title' => 'Safari désert à Dubaï', 'slug' => 'safari-desert-dubai', 'country' => 'Émirats Arabes Unis', 'city' => 'Dubaï', 'category' => 'Aventure', 'duration_label' => 'Demi-journée', 'badge' => 'À la une', 'short_description' => 'Safari dans le désert avec transport, dunes et expérience locale.', 'includes' => ['Transport', 'Guide', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80', 'price_from' => 650, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => true, 'is_active' => true, 'sort_order' => 4],
            ['title' => 'Visite guidée de la médina de Fès', 'slug' => 'visite-medina-fes', 'country' => 'Maroc', 'city' => 'Fès', 'category' => 'Culture', 'duration_label' => '3 heures', 'badge' => 'Culture', 'short_description' => 'Découverte de la médina de Fès avec un guide local.', 'includes' => ['Guide local', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f56?auto=format&fit=crop&w=1200&q=80', 'price_from' => 180, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 5],
            ['title' => 'Balade en chameau à Marrakech', 'slug' => 'balade-chameau-marrakech', 'country' => 'Maroc', 'city' => 'Marrakech', 'category' => 'Famille', 'duration_label' => '1 heure', 'badge' => 'Famille', 'short_description' => 'Balade en chameau adaptée aux familles avec assistance locale.', 'includes' => ['Guide', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1508675801627-066ac4346a55?auto=format&fit=crop&w=1200&q=80', 'price_from' => 150, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 6],
            ['title' => 'Journée plage et détente à Agadir', 'slug' => 'journee-plage-agadir', 'country' => 'Maroc', 'city' => 'Agadir', 'category' => 'Nature', 'duration_label' => 'Journée complète', 'badge' => 'Nature', 'short_description' => 'Journée détente à Agadir avec recommandations Ajinsafro.', 'includes' => ['Assistance Ajinsafro', 'Conseils locaux'], 'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', 'price_from' => 120, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 7],
            ['title' => 'Visite de Chefchaouen en journée', 'slug' => 'visite-chefchaouen-journee', 'country' => 'Maroc', 'city' => 'Chefchaouen', 'category' => 'Culture', 'duration_label' => 'Journée complète', 'badge' => 'Culture', 'short_description' => 'Découverte de la ville bleue et de ses ruelles avec guide optionnel.', 'includes' => ['Guide optionnel', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&w=1200&q=80', 'price_from' => 220, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 8],
            ['title' => 'Tour historique de Tanger', 'slug' => 'tour-historique-tanger', 'country' => 'Maroc', 'city' => 'Tanger', 'category' => 'Culture', 'duration_label' => '3 heures', 'badge' => 'Culture', 'short_description' => 'Visite historique de Tanger, kasbah, médina et points panoramiques.', 'includes' => ['Guide local', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80', 'price_from' => 200, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 9],
            ['title' => 'City tour Casablanca', 'slug' => 'city-tour-casablanca', 'country' => 'Maroc', 'city' => 'Casablanca', 'category' => 'Culture', 'duration_label' => 'Demi-journée', 'badge' => 'City tour', 'short_description' => 'Découverte de Casablanca, corniche, centre-ville et monuments principaux.', 'includes' => ['Guide optionnel', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1526481280695-3c4691f52af6?auto=format&fit=crop&w=1200&q=80', 'price_from' => 230, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 10],
            ['title' => 'Montgolfière en Cappadoce', 'slug' => 'montgolfiere-cappadoce', 'country' => 'Turquie', 'city' => 'Cappadoce', 'category' => 'Aventure', 'duration_label' => '2 heures', 'badge' => 'Premium', 'short_description' => 'Expérience en montgolfière au lever du soleil en Cappadoce.', 'includes' => ['Transport', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80', 'price_from' => 1800, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 11],
            ['title' => 'Excursion bateau à Antalya', 'slug' => 'excursion-bateau-antalya', 'country' => 'Turquie', 'city' => 'Antalya', 'category' => 'Mer & bateau', 'duration_label' => 'Journée complète', 'badge' => 'Mer & bateau', 'short_description' => 'Sortie en bateau sur la côte d’Antalya avec pauses baignade.', 'includes' => ['Bateau', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80', 'price_from' => 450, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 12],
            ['title' => 'Visite guidée de Barcelone', 'slug' => 'visite-guidee-barcelone', 'country' => 'Espagne', 'city' => 'Barcelone', 'category' => 'Culture', 'duration_label' => 'Demi-journée', 'badge' => 'Culture', 'short_description' => 'Découverte des incontournables de Barcelone avec guide local.', 'includes' => ['Guide local', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1200&q=80', 'price_from' => 350, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 13],
            ['title' => 'Tour tapas à Madrid', 'slug' => 'tour-tapas-madrid', 'country' => 'Espagne', 'city' => 'Madrid', 'category' => 'Gastronomie', 'duration_label' => '3 heures', 'badge' => 'Gastronomie', 'short_description' => 'Expérience gastronomique à Madrid autour des tapas.', 'includes' => ['Guide', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80', 'price_from' => 420, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 14],
            ['title' => 'Découverte de Séville', 'slug' => 'decouverte-seville', 'country' => 'Espagne', 'city' => 'Séville', 'category' => 'Culture', 'duration_label' => 'Demi-journée', 'badge' => 'Culture', 'short_description' => 'Visite de Séville, ses quartiers historiques et son ambiance andalouse.', 'includes' => ['Guide optionnel', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1515442261605-65987783cb6a?auto=format&fit=crop&w=1200&q=80', 'price_from' => 330, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 15],
            ['title' => 'Croisière sur la Seine à Paris', 'slug' => 'croisiere-seine-paris', 'country' => 'France', 'city' => 'Paris', 'category' => 'Mer & bateau', 'duration_label' => '1 heure', 'badge' => 'À découvrir', 'short_description' => 'Croisière panoramique sur la Seine pour découvrir Paris autrement.', 'includes' => ['Billet', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=80', 'price_from' => 280, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 16],
            ['title' => 'Tour de Nice et Côte d’Azur', 'slug' => 'tour-nice-cote-azur', 'country' => 'France', 'city' => 'Nice', 'category' => 'Nature', 'duration_label' => 'Demi-journée', 'badge' => 'Nature', 'short_description' => 'Découverte de Nice et des paysages de la Côte d’Azur.', 'includes' => ['Guide optionnel', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80', 'price_from' => 500, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 17],
            ['title' => 'Visite moderne de Lyon', 'slug' => 'visite-moderne-lyon', 'country' => 'France', 'city' => 'Lyon', 'category' => 'Culture', 'duration_label' => '3 heures', 'badge' => 'Culture', 'short_description' => 'Balade urbaine à Lyon entre patrimoine, gastronomie et quartiers modernes.', 'includes' => ['Guide local', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1529243856184-fd5465488984?auto=format&fit=crop&w=1200&q=80', 'price_from' => 300, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 18],
            ['title' => 'Abu Dhabi city tour', 'slug' => 'abu-dhabi-city-tour', 'country' => 'Émirats Arabes Unis', 'city' => 'Abu Dhabi', 'category' => 'Culture', 'duration_label' => 'Journée complète', 'badge' => 'City tour', 'short_description' => 'Découverte d’Abu Dhabi, mosquée, corniche et lieux incontournables.', 'includes' => ['Transport', 'Guide', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?auto=format&fit=crop&w=1200&q=80', 'price_from' => 750, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 19],
            ['title' => 'Billet Burj Khalifa Dubaï', 'slug' => 'billet-burj-khalifa-dubai', 'country' => 'Émirats Arabes Unis', 'city' => 'Dubaï', 'category' => 'Famille', 'duration_label' => '2 heures', 'badge' => 'Billet', 'short_description' => 'Accès au Burj Khalifa avec assistance Ajinsafro pour la réservation.', 'includes' => ['Billet', 'Assistance Ajinsafro'], 'image_url' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80', 'price_from' => 600, 'currency' => 'MAD', 'availability_label' => 'Disponible', 'is_featured' => false, 'is_active' => true, 'sort_order' => 20],
        ];

        foreach ($rows as $row) {
            ActivityOffer::updateOrCreate(
                ['slug' => $row['slug']],
                $row
            );
        }
    }
}
