<?php

return [
    'items' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'icon' => 'bx bx-home-circle',
            'permission' => 'dashboard.view',
            'children' => [
                ['label' => 'Vue d\'ensemble', 'route' => 'admin.dashboard.vue-globale', 'permission' => 'dashboard.overview.view'],
                ['label' => 'Statistiques', 'route' => 'admin.dashboard.statistiques', 'permission' => 'dashboard.stats.view'],
                ['label' => 'Alertes', 'route' => 'admin.dashboard.alertes', 'permission' => 'dashboard.alerts.view'],
            ],
        ],
        [
            'key' => 'reservations',
            'label' => 'Réservations',
            'icon' => 'bx bx-calendar-check',
            'permission' => 'reservations.view',
            'route' => 'admin.reservations.workspace',
            'active_patterns' => ['admin.reservations.*'],
        ],
        [
            'key' => 'messagerie',
            'label' => 'Messagerie',
            'icon' => 'bx bx-envelope',
            'permission' => 'dashboard.view',
            'route' => 'admin.messagerie.index',
            'active_patterns' => ['admin.messagerie.*'],
        ],
        [
            'key' => 'customers',
            'label' => 'Clients',
            'icon' => 'bx bx-user',
            'permission' => 'customers.view',
            'children' => [
                ['label' => 'Liste clients', 'route' => 'admin.customers.clients', 'permission' => 'customers.clients.view'],
                ['label' => 'Voyageurs', 'route' => 'admin.customers.voyageurs', 'permission' => 'customers.travelers.view'],
                ['label' => 'Historique', 'route' => 'admin.customers.historique', 'permission' => 'customers.history.view'],
                ['label' => 'Fidélité', 'route' => 'admin.customers.fidelite', 'permission' => 'customers.loyalty.view'],
            ],
        ],
        [
            'key' => 'products',
            'label' => 'Grille commerciale',
            'icon' => 'bx bx-store',
            'permission' => 'products.view',
            'children' => [
                ['label' => 'Tarifs', 'route' => 'admin.products.tarifs', 'permission' => 'products.pricing.view'],
                ['label' => 'Services', 'route' => 'admin.products.services', 'permission' => 'products.services.view'],
                ['label' => 'Conditions', 'route' => 'admin.products.conditions', 'permission' => 'products.conditions.view'],
                ['label' => 'Options', 'route' => 'admin.products.options', 'permission' => 'products.options.view'],
            ],
        ],
        [
            'key' => 'products_services',
            'label' => 'Produits & Services',
            'icon' => 'bx bx-layer',
            'permission' => 'products-services.view',
            'children' => [
                [
                    'key' => 'voyages',
                    'label' => 'Voyages',
                    'icon' => 'bx bx-plane',
                    'permission' => 'circuits.voyages.view',
                    'children' => [
                        ['label' => 'Tous les voyages', 'route' => 'admin.circuits.voyages.index', 'permission' => 'circuits.voyages.view'],
                        ['label' => 'Départs / disponibilités', 'route' => 'admin.circuits.departs-dates', 'permission' => 'circuits.departures.view'],
                        ['label' => 'Hôtels circuit', 'route' => 'admin.circuits.tour-hotels.index', 'permission' => 'circuits.tour-hotels.view'],
                        ['label' => 'Chambres', 'route' => 'admin.accommodations.chambres', 'permission' => 'accommodations.rooms.view'],
                        ['label' => 'Tarifs / disponibilités', 'route' => 'admin.accommodations.tarifs-saisonniers', 'permission' => 'accommodations.seasonal-pricing.view'],
                    ],
                ],
                [
                    'key' => 'group_deals',
                    'label' => 'Group Deals',
                    'icon' => 'bx bx-group',
                    'permission' => 'group-deals.view',
                    'children' => [
                        ['label' => 'Catalogue Group Deals', 'route' => 'admin.group-deals.index', 'permission' => 'group-deals.offers.view', 'active_patterns' => ['admin.group-deals.index', 'admin.group-deals.create', 'admin.group-deals.store', 'admin.group-deals.show', 'admin.group-deals.edit', 'admin.group-deals.update', 'admin.group-deals.destroy', 'admin.group-deals.recalculate']],
                        ['label' => 'Voyages GD', 'route' => 'admin.group-deals.trips.index', 'permission' => 'group-deals.trips.view', 'active_patterns' => ['admin.group-deals.trips.*']],
                        ['label' => 'Départs GD', 'route' => 'admin.group-deals.departures.index', 'permission' => 'group-deals.departures.view', 'active_patterns' => ['admin.group-deals.departures.index', 'admin.group-deals.departures.show', 'admin.group-deals.departures.recalculate']],
                        ['label' => 'Participants / inscriptions', 'route' => 'admin.group-deals.participants.index', 'permission' => 'group-deals.participants.view', 'active_patterns' => ['admin.group-deals.participants.*', 'admin.group-deals.departures.participants.*']],
                        ['label' => 'Tarifs par palier', 'route' => 'admin.group-deals.tiers.index', 'permission' => 'group-deals.tiers.view', 'active_patterns' => ['admin.group-deals.tiers.*', 'admin.group-deals.trips.tiers.*']],
                    ],
                ],
                [
                    'key' => 'accommodations',
                    'label' => 'Hébergements',
                    'icon' => 'bx bx-hotel',
                    'permission' => 'accommodations.view',
                    'children' => [
                        ['label' => 'Tous les hébergements', 'route' => 'admin.accommodations.hotels', 'permission' => 'accommodations.catalog.view'],
                        ['label' => 'Hôtels WordPress', 'route' => 'admin.wordpress.hotels.index', 'permission' => 'accommodations.wordpress-hotels.view'],
                        ['label' => 'Packs hébergement', 'route' => 'admin.accommodation-packages.index', 'permission' => 'accommodations.packages.view'],
                        ['label' => 'Chambres', 'route' => 'admin.accommodations.chambres', 'permission' => 'accommodations.rooms.view'],
                        ['label' => 'Tarifs saisonniers', 'route' => 'admin.accommodations.tarifs-saisonniers', 'permission' => 'accommodations.seasonal-pricing.view'],
                        ['label' => 'Disponibilités', 'route' => 'admin.accommodations.disponibilites', 'permission' => 'accommodations.availability.view'],
                    ],
                ],
                [
                    'key' => 'hajj_omra',
                    'label' => 'Hajj & Omra',
                    'icon' => 'bx bx-building-house',
                    'permission' => 'hajj-omra.view',
                    'children' => [
                        ['label' => 'Toutes les offres', 'route' => 'admin.hajj-omra.index', 'permission' => 'hajj-omra.view', 'active_patterns' => ['admin.hajj-omra.index', 'admin.hajj-omra.create', 'admin.hajj-omra.store', 'admin.hajj-omra.show', 'admin.hajj-omra.edit', 'admin.hajj-omra.update', 'admin.hajj-omra.destroy']],
                        ['label' => 'Demandes', 'route' => 'admin.hajj-omra.requests.index', 'permission' => 'hajj-omra.requests.view', 'active_patterns' => ['admin.hajj-omra.requests.*']],
                    ],
                ],
                [
                    'key' => 'economic_offers',
                    'label' => 'Formule Ã‰conomique',
                    'icon' => 'bx bx-wallet-alt',
                    'permission' => 'economic-offers.view',
                    'children' => [
                        ['label' => 'Toutes les offres', 'route' => 'admin.economic-offers.index', 'permission' => 'economic-offers.view', 'active_patterns' => ['admin.economic-offers.index', 'admin.economic-offers.create', 'admin.economic-offers.store', 'admin.economic-offers.show', 'admin.economic-offers.edit', 'admin.economic-offers.update', 'admin.economic-offers.destroy']],
                        ['label' => 'Demandes', 'route' => 'admin.economic-offers.requests.index', 'permission' => 'economic-offers.requests.view', 'active_patterns' => ['admin.economic-offers.requests.*']],
                    ],
                ],
                [
                    'key' => 'activities',
                    'label' => 'Activités',
                    'icon' => 'bx bx-camera',
                    'permission' => 'activities.view',
                    'children' => [
                        ['label' => 'Offres activités', 'route' => 'admin.activity-offers.index', 'permission' => 'activities.offers.view'],
                        ['label' => 'Catégories', 'route' => 'admin.activities.categories', 'permission' => 'activities.categories.view'],
                        ['label' => 'Images / galerie', 'route' => 'admin.activities.gallery', 'permission' => 'activities.gallery.view'],
                        ['label' => 'Disponibilités', 'route' => 'admin.activities.availability', 'permission' => 'activities.availability.view'],
                    ],
                ],
                [
                    'key' => 'transfers',
                    'label' => 'Transferts',
                    'icon' => 'bx bx-car',
                    'permission' => 'transfers.view',
                    'children' => [
                        ['label' => 'Offres transfert', 'route' => 'admin.circuits.tour-transfers.index', 'permission' => 'transfers.offers.view'],
                        ['label' => 'Véhicules', 'route' => 'admin.transfers.vehicles', 'permission' => 'transfers.vehicles.view'],
                        ['label' => 'Tarifs', 'route' => 'admin.transfers.pricing', 'permission' => 'transfers.pricing.view'],
                        ['label' => 'Disponibilités', 'route' => 'admin.transfers.availability', 'permission' => 'transfers.availability.view'],
                    ],
                ],
            ],
        ],
        [
            'key' => 'operations',
            'label' => 'Opérations Terrain',
            'icon' => 'bx bx-briefcase-alt-2',
            'permission' => 'operations.view',
            'children' => [
                ['label' => 'Planning', 'route' => 'admin.operations.planning', 'permission' => 'operations.planning.view'],
                ['label' => 'Véhicules', 'route' => 'admin.operations.vehicules', 'permission' => 'operations.vehicles.view'],
                ['label' => 'Guides & Chauffeurs', 'route' => 'admin.operations.guides-chauffeurs', 'permission' => 'operations.guides.view'],
                ['label' => 'Logistique', 'route' => 'admin.operations.logistique', 'permission' => 'operations.logistics.view'],
            ],
        ],
        [
            'key' => 'visa',
            'label' => 'Visa',
            'icon' => 'bx bx-id-card',
            'permission' => 'visa.view',
            'children' => [
                ['label' => 'Demandes de visa', 'route' => 'admin.visa.demandes-visa', 'permission' => 'visa.requests.view'],
                ['label' => 'Documents', 'route' => 'admin.visa.documents', 'permission' => 'visa.documents.view'],
                ['label' => 'Statuts', 'route' => 'admin.visa.statuts', 'permission' => 'visa.statuses.view'],
            ],
        ],
        [
            'key' => 'finance',
            'label' => 'Finance',
            'icon' => 'bx bx-wallet',
            'permission' => 'finance.view',
            'children' => [
                ['label' => 'Factures', 'route' => 'admin.finance.factures', 'permission' => 'finance.invoices.view'],
                ['label' => 'Paiements', 'route' => 'admin.finance.paiements', 'permission' => 'finance.payments.view'],
                ['label' => 'Dépenses', 'route' => 'admin.finance.depenses', 'permission' => 'finance.expenses.view'],
                ['label' => 'Commissions', 'route' => 'admin.finance.commissions', 'permission' => 'finance.commissions.view'],
                ['label' => 'Rapports financiers', 'route' => 'admin.finance.rapports-financiers', 'permission' => 'finance.reports.view'],
            ],
        ],
        [
            'key' => 'partners',
            'label' => 'Partenaires',
            'icon' => 'bx bx-group',
            'permission' => 'partners.view',
            'children' => [
                ['label' => 'Partenaires', 'route' => 'admin.partners.partenaires', 'permission' => 'partners.list.view'],
                ['label' => 'Fournisseurs', 'route' => 'admin.partners.fournisseurs', 'permission' => 'partners.suppliers.view'],
                ['label' => 'Contrats', 'route' => 'admin.partners.contrats', 'permission' => 'partners.contracts.view'],
            ],
        ],
        [
            'key' => 'reporting',
            'label' => 'Reporting',
            'icon' => 'bx bx-bar-chart-alt-2',
            'permission' => 'reporting.view',
            'children' => [
                ['label' => 'Rapports', 'route' => 'admin.reporting.rapports', 'permission' => 'reporting.reports.view'],
                ['label' => 'Tableaux de bord', 'route' => 'admin.reporting.tableaux-bord', 'permission' => 'reporting.dashboards.view'],
                ['label' => 'Exports', 'route' => 'admin.reporting.exports', 'permission' => 'reporting.exports.view'],
            ],
        ],
        [
            'key' => 'settings',
            'label' => 'Paramètres',
            'icon' => 'bx bx-cog',
            'permission' => 'settings.view',
            'children' => [
                ['label' => 'Utilisateurs', 'route' => 'admin.settings.utilisateurs', 'permission' => 'settings.users.manage'],
                ['label' => 'Rôles & Permissions', 'route' => 'admin.settings.roles-permissions', 'permission' => 'settings.roles.manage'],
                ['label' => 'Paramètres généraux', 'route' => 'admin.settings.parametres-generaux', 'permission' => 'settings.general.manage'],
                ['label' => 'Référentiels métier', 'route' => 'admin.settings.referentiels-metier', 'permission' => 'settings.general.manage'],
                ['label' => 'Home page', 'route' => 'admin.settings.home-page.edit', 'permission' => 'settings.general.manage'],
                ['label' => 'Sécurité', 'route' => 'admin.settings.securite', 'permission' => 'settings.security.manage'],
            ],
        ],
    ],

    'route_permissions' => [
        'admin.dashboard' => 'dashboard.view',
        'admin.profile.edit' => 'dashboard.view',
        'admin.profile.update' => 'dashboard.view',
        'admin.profile.avatar' => 'dashboard.view',

        'admin.circuits.index' => 'circuits.voyages.view',
        'admin.circuits.circuits' => 'circuits.voyages.view',
        'admin.circuits.itineraires' => 'circuits.voyages.view',
        'admin.circuits.options' => 'circuits.voyages.view',
        'admin.circuits.politiques-conditions' => 'circuits.voyages.view',
        'admin.circuits.departs-dates' => 'circuits.departures.view',

        'admin.accommodations.index' => 'accommodations.view',
        'admin.accommodations.hotels' => 'accommodations.catalog.view',
        'admin.accommodations.chambres' => 'accommodations.rooms.view',
        'admin.accommodations.tarifs-saisonniers' => 'accommodations.seasonal-pricing.view',
        'admin.accommodations.disponibilites' => 'accommodations.availability.view',

        'admin.wordpress.hotels.index' => 'accommodations.wordpress-hotels.view',
        'admin.wordpress.hotels.create' => 'accommodations.wordpress-hotels.view',
        'admin.wordpress.hotels.store' => 'accommodations.wordpress-hotels.view',
        'admin.wordpress.hotels.edit' => 'accommodations.wordpress-hotels.view',
        'admin.wordpress.hotels.update' => 'accommodations.wordpress-hotels.view',
        'admin.wordpress.hotels.destroy' => 'accommodations.wordpress-hotels.view',

        'admin.activities.categories' => 'activities.categories.view',
        'admin.activities.gallery' => 'activities.gallery.view',
        'admin.activities.availability' => 'activities.availability.view',
        'admin.transfers.vehicles' => 'transfers.vehicles.view',
        'admin.transfers.pricing' => 'transfers.pricing.view',
        'admin.transfers.availability' => 'transfers.availability.view',

        'admin.group-deals.participants.index' => 'group-deals.participants.view',
        'admin.group-deals.participants.store' => 'group-deals.participants.view',
        'admin.group-deals.participants.update' => 'group-deals.participants.view',
        'admin.hajj-omra.requests.index' => 'hajj-omra.requests.view',
        'admin.hajj-omra.requests.show' => 'hajj-omra.requests.view',
        'admin.hajj-omra.requests.update' => 'hajj-omra.requests.view',
        'admin.economic-offers.requests.index' => 'economic-offers.requests.view',
        'admin.economic-offers.requests.show' => 'economic-offers.requests.view',
        'admin.economic-offers.requests.update' => 'economic-offers.requests.view',
        'admin.group-deals.tiers.index' => 'group-deals.tiers.view',
        'admin.group-deals.tiers.store' => 'group-deals.tiers.view',
        'admin.group-deals.tiers.update' => 'group-deals.tiers.view',
        'admin.group-deals.trips.tiers.store' => 'group-deals.tiers.view',
        'admin.group-deals.trips.tiers.update' => 'group-deals.tiers.view',
        'admin.group-deals.trips.tiers.destroy' => 'group-deals.tiers.view',
        'admin.group-deals.departures.participants.store' => 'group-deals.participants.view',
        'admin.group-deals.departures.participants.update' => 'group-deals.participants.view',
        'admin.group-deals.departures.recalculate' => 'group-deals.departures.view',

        'admin.settings.index' => 'settings.view',
        'admin.settings.parametres-generaux.update' => 'settings.general.manage',
        'admin.settings.referentiels-metier' => 'settings.general.manage',
        'admin.settings.referentiels-metier.group' => 'settings.general.manage',
        'admin.settings.referentiels-metier.store' => 'settings.general.manage',
        'admin.settings.referentiels-metier.update' => 'settings.general.manage',
        'admin.settings.referentiels-metier.destroy' => 'settings.general.manage',
        'admin.settings.referentiels-metier.import-legacy' => 'settings.general.manage',
        'admin.settings.home-page.edit' => 'settings.general.manage',
        'admin.settings.home-page.update' => 'settings.general.manage',
        'admin.settings.utilisateurs.create' => 'settings.users.manage',
        'admin.settings.utilisateurs' => 'settings.users.manage',
        'admin.settings.utilisateurs.store' => 'settings.users.manage',
        'admin.settings.utilisateurs.edit' => 'settings.users.manage',
        'admin.settings.utilisateurs.update' => 'settings.users.manage',
        'admin.settings.utilisateurs.toggle-active' => 'settings.users.manage',
        'admin.settings.utilisateurs.destroy' => 'settings.users.manage',
        'admin.settings.roles-permissions' => 'settings.roles.manage',
        'admin.settings.roles-permissions.create' => 'settings.roles.manage',
        'admin.settings.roles-permissions.store' => 'settings.roles.manage',
        'admin.settings.roles-permissions.edit' => 'settings.roles.manage',
        'admin.settings.roles-permissions.update' => 'settings.roles.manage',
        'admin.settings.roles-permissions.destroy' => 'settings.roles.manage',
    ],

    'route_prefix_permissions' => [
        'admin.dashboard.' => 'dashboard.view',
        'admin.reservations.' => 'reservations.view',
        'admin.customers.' => 'customers.view',
        'admin.products.' => 'products.view',
        'admin.circuits.voyages.' => 'circuits.voyages.view',
        'admin.circuits.voyage-themes.' => 'circuits.voyages.view',
        'admin.circuits.taxonomy-terms.' => 'circuits.voyages.view',
        'admin.circuits.airlines.' => 'circuits.voyages.view',
        'admin.circuits.activities.' => 'activities.offers.view',
        'admin.circuits.wp-hotels.' => 'circuits.tour-hotels.view',
        'admin.circuits.tour-hotels.' => 'circuits.tour-hotels.view',
        'admin.circuits.tour-transfers.' => 'transfers.offers.view',
        'admin.accommodations.' => 'accommodations.view',
        'admin.accommodation-packages.' => 'accommodations.packages.view',
        'admin.hajj-omra.requests.' => 'hajj-omra.requests.view',
        'admin.hajj-omra.' => 'hajj-omra.view',
        'admin.economic-offers.requests.' => 'economic-offers.requests.view',
        'admin.economic-offers.' => 'economic-offers.view',
        'admin.activity-offers.' => 'activities.offers.view',
        'admin.wordpress.hotels.' => 'accommodations.wordpress-hotels.view',
        'admin.wordpress.tours.' => 'circuits.voyages.view',
        'admin.wordpress.activities.' => 'activities.offers.view',
        'admin.wordpress.transfers.' => 'transfers.offers.view',
        'admin.operations.' => 'operations.view',
        'admin.visa.' => 'visa.view',
        'admin.finance.' => 'finance.view',
        'admin.partners.' => 'partners.view',
        'admin.reporting.' => 'reporting.view',
        'admin.settings.' => 'settings.view',
        'admin.group-deals.trips.' => 'group-deals.trips.view',
        'admin.group-deals.departures.' => 'group-deals.departures.view',
        'admin.group-deals.' => 'group-deals.offers.view',
    ],
];
