<?php

return [
    'items' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'icon' => 'bx bx-home-circle',
            'permission' => 'dashboard.view',
            'children' => [
                ['label' => 'Vue d\'ensemble', 'route' => 'admin.dashboard.vue-globale', 'permission' => 'dashboard.overview.view'],
                ['label' => 'Statistiques', 'route' => 'admin.dashboard.statistiques', 'permission' => 'dashboard.stats.view'],
                ['label' => 'Alertes', 'route' => 'admin.dashboard.alertes', 'permission' => 'dashboard.alerts.view'],
            ],
        ],
        [
            'key' => 'reservations',
            'label' => 'Réservations',
            'icon' => 'bx bx-calendar-check',
            'permission' => 'reservations.view',
            'route' => 'admin.reservations.workspace',
        ],
        [
            'key' => 'messagerie',
            'label' => 'Messagerie',
            'icon' => 'bx bx-envelope',
            'permission' => 'dashboard.view',
            'route' => 'admin.messagerie.index',
        ],
        [
            'key' => 'customers',
            'label' => 'Clients',
            'icon' => 'bx bx-user',
            'permission' => 'customers.view',
            'children' => [
                ['label' => 'Clients', 'route' => 'admin.customers.clients', 'permission' => 'customers.clients.view'],
                ['label' => 'Voyageurs', 'route' => 'admin.customers.voyageurs', 'permission' => 'customers.travelers.view'],
                ['label' => 'Historique', 'route' => 'admin.customers.historique', 'permission' => 'customers.history.view'],
                ['label' => 'Avis clients', 'route' => 'admin.customers.avis-clients', 'permission' => 'customers.reviews.view'],
                ['label' => 'Fidélité', 'route' => 'admin.customers.fidelite', 'permission' => 'customers.loyalty.view'],
            ],
        ],
        [
            'key' => 'products',
            'label' => 'Grille commerciale',
            'icon' => 'bx bx-store',
            'permission' => 'products.view',
            'children' => [
                ['label' => 'Services', 'route' => 'admin.products.services', 'permission' => 'products.services.view'],
                ['label' => 'Options', 'route' => 'admin.products.options', 'permission' => 'products.options.view'],
                ['label' => 'Tarifs', 'route' => 'admin.products.tarifs', 'permission' => 'products.pricing.view'],
                ['label' => 'Conditions', 'route' => 'admin.products.conditions', 'permission' => 'products.conditions.view'],
            ],
        ],
        [
            'key' => 'products_services',
            'label' => 'Produit & Service',
            'icon' => 'bx bx-layer',
            'permission' => 'circuits.view',
            'children' => [
                ['label' => 'Voyage', 'route' => 'admin.circuits.voyages.index', 'permission' => 'circuits.voyages.view'],
                ['label' => 'Billetterie', 'route' => 'admin.products-services.billetterie', 'permission' => 'circuits.view'],
                ['label' => 'Hébergement', 'route' => 'admin.wordpress.hotels.index', 'permission' => 'wordpress.view'],
                ['label' => 'Activités (catalogue)', 'route' => 'admin.wordpress.activities.index', 'permission' => 'wordpress.view'],
                ['label' => 'Transfert (catalogue)', 'route' => 'admin.wordpress.transfers.index', 'permission' => 'wordpress.view'],
                ['label' => 'Activité', 'route' => 'admin.circuits.activities.index', 'permission' => 'circuits.activities.view'],
                ['label' => 'Transfert', 'route' => 'admin.circuits.tour-transfers.index', 'permission' => 'circuits.tour-transfers.view'],
                ['label' => 'Voiture', 'route' => 'admin.products-services.voiture', 'permission' => 'circuits.view'],
                ['label' => 'Départs / disponibilités', 'route' => 'admin.circuits.departs-dates', 'permission' => 'circuits.view'],
            ],
        ],
        [
            'key' => 'accommodations',
            'label' => 'Hébergements',
            'icon' => 'bx bx-hotel',
            'permission' => 'accommodations.view',
            'children' => [
                ['label' => 'Hôtels (circuit)', 'route' => 'admin.circuits.tour-hotels.index', 'permission' => 'circuits.tour-hotels.view'],
                ['label' => 'Chambres', 'route' => 'admin.accommodations.chambres', 'permission' => 'accommodations.rooms.view'],
                ['label' => 'Tarifs saisonniers', 'route' => 'admin.accommodations.tarifs-saisonniers', 'permission' => 'accommodations.seasonal-pricing.view'],
                ['label' => 'Disponibilités', 'route' => 'admin.accommodations.disponibilites', 'permission' => 'accommodations.availability.view'],
            ],
        ],
        [
            'key' => 'operations',
            'label' => 'Opérations Terrain',
            'icon' => 'bx bx-briefcase-alt-2',
            'permission' => 'operations.view',
            'children' => [
                ['label' => 'Planning', 'route' => 'admin.operations.planning', 'permission' => 'operations.planning.view'],
                ['label' => 'Guides & Chauffeurs', 'route' => 'admin.operations.guides-chauffeurs', 'permission' => 'operations.guides.view'],
                ['label' => 'Véhicules', 'route' => 'admin.operations.vehicules', 'permission' => 'operations.vehicles.view'],
                ['label' => 'Logistique', 'route' => 'admin.operations.logistique', 'permission' => 'operations.logistics.view'],
            ],
        ],
        [
            'key' => 'visa',
            'label' => 'Visa',
            'icon' => 'bx bx-id-card',
            'permission' => 'visa.view',
            'children' => [
                ['label' => 'Demandes de visa', 'route' => 'admin.visa.demandes-visa', 'permission' => 'visa.requests.view'],
                ['label' => 'Statuts', 'route' => 'admin.visa.statuts', 'permission' => 'visa.statuses.view'],
                ['label' => 'Documents', 'route' => 'admin.visa.documents', 'permission' => 'visa.documents.view'],
            ],
        ],
        [
            'key' => 'finance',
            'label' => 'Finance',
            'icon' => 'bx bx-wallet',
            'permission' => 'finance.view',
            'children' => [
                ['label' => 'Factures', 'route' => 'admin.finance.factures', 'permission' => 'finance.invoices.view'],
                ['label' => 'Paiements', 'route' => 'admin.finance.paiements', 'permission' => 'finance.payments.view'],
                ['label' => 'Dépenses', 'route' => 'admin.finance.depenses', 'permission' => 'finance.expenses.view'],
                ['label' => 'Commissions', 'route' => 'admin.finance.commissions', 'permission' => 'finance.commissions.view'],
                ['label' => 'Rapports financiers', 'route' => 'admin.finance.rapports-financiers', 'permission' => 'finance.reports.view'],
            ],
        ],
        [
            'key' => 'partners',
            'label' => 'Partenaires',
            'icon' => 'bx bx-group',
            'permission' => 'partners.view',
            'children' => [
                ['label' => 'Partenaires', 'route' => 'admin.partners.partenaires', 'permission' => 'partners.list.view'],
                ['label' => 'Fournisseurs', 'route' => 'admin.partners.fournisseurs', 'permission' => 'partners.suppliers.view'],
                ['label' => 'Contrats', 'route' => 'admin.partners.contrats', 'permission' => 'partners.contracts.view'],
            ],
        ],
        [
            'key' => 'reporting',
            'label' => 'Reporting',
            'icon' => 'bx bx-bar-chart-alt-2',
            'permission' => 'reporting.view',
            'children' => [
                ['label' => 'Rapports', 'route' => 'admin.reporting.rapports', 'permission' => 'reporting.reports.view'],
                ['label' => 'Tableaux de bord', 'route' => 'admin.reporting.tableaux-bord', 'permission' => 'reporting.dashboards.view'],
                ['label' => 'Exports', 'route' => 'admin.reporting.exports', 'permission' => 'reporting.exports.view'],
            ],
        ],
        [
            'key' => 'wordpress',
            'label' => 'WordPress',
            'icon' => 'bx bx-wordpress',
            'permission' => 'wordpress.view',
            'children' => [
                ['label' => 'Hotels', 'route' => 'admin.wordpress.hotels.index', 'permission' => 'wordpress.hotels.view'],
                ['label' => 'Activities', 'route' => 'admin.wordpress.activities.index', 'permission' => 'wordpress.view'],
                ['label' => 'Transfers', 'route' => 'admin.wordpress.transfers.index', 'permission' => 'wordpress.view'],
            ],
        ],
        [
            'key' => 'settings',
            'label' => 'Paramètres',
            'icon' => 'bx bx-cog',
            'permission' => 'settings.view',
            'children' => [
                ['label' => 'Utilisateurs', 'route' => 'admin.settings.utilisateurs', 'permission' => 'settings.users.manage'],
                ['label' => 'Rôles & Permissions', 'route' => 'admin.settings.roles-permissions', 'permission' => 'settings.roles.manage'],
                ['label' => 'Paramètres généraux', 'route' => 'admin.settings.parametres-generaux', 'permission' => 'settings.general.manage'],
                ['label' => 'Référentiels métier', 'route' => 'admin.settings.referentiels-metier', 'permission' => 'settings.general.manage'],
                ['label' => 'Home page', 'route' => 'admin.settings.home-page.edit', 'permission' => 'settings.general.manage'],
                ['label' => 'Sécurité', 'route' => 'admin.settings.securite', 'permission' => 'settings.security.manage'],
            ],
        ],
    ],

    'route_permissions' => [
        'admin.dashboard' => 'dashboard.view',
        'admin.settings.index' => 'settings.view',
        'admin.settings.parametres-generaux.update' => 'settings.general.manage',
        'admin.settings.referentiels-metier' => 'settings.general.manage',
        'admin.settings.referentiels-metier.group' => 'settings.general.manage',
        'admin.settings.referentiels-metier.store' => 'settings.general.manage',
        'admin.settings.referentiels-metier.update' => 'settings.general.manage',
        'admin.settings.referentiels-metier.destroy' => 'settings.general.manage',
        'admin.settings.referentiels-metier.import-legacy' => 'settings.general.manage',
        'admin.settings.home-page.edit' => 'settings.general.manage',
        'admin.settings.home-page.update' => 'settings.general.manage',

        'admin.profile.edit' => 'dashboard.view',
        'admin.profile.update' => 'dashboard.view',
        'admin.profile.avatar' => 'dashboard.view',

        'admin.settings.utilisateurs.create' => 'settings.users.manage',
        'admin.settings.utilisateurs' => 'settings.users.manage',
        'admin.settings.utilisateurs.store' => 'settings.users.manage',
        'admin.settings.utilisateurs.edit' => 'settings.users.manage',
        'admin.settings.utilisateurs.update' => 'settings.users.manage',
        'admin.settings.utilisateurs.toggle-active' => 'settings.users.manage',
        'admin.settings.utilisateurs.destroy' => 'settings.users.manage',

        'admin.settings.roles-permissions' => 'settings.roles.manage',
        'admin.settings.roles-permissions.create' => 'settings.roles.manage',
        'admin.settings.roles-permissions.store' => 'settings.roles.manage',
        'admin.settings.roles-permissions.edit' => 'settings.roles.manage',
        'admin.settings.roles-permissions.update' => 'settings.roles.manage',
        'admin.settings.roles-permissions.destroy' => 'settings.roles.manage',
    ],

    'route_prefix_permissions' => [
        'admin.dashboard.' => 'dashboard.view',
        'admin.reservations.' => 'reservations.view',
        'admin.customers.' => 'customers.view',
        'admin.products.' => 'products.view',
        'admin.products-services.' => 'circuits.view',
        'admin.circuits.' => 'circuits.view',
        'admin.accommodations.' => 'accommodations.view',
        'admin.operations.' => 'operations.view',
        'admin.visa.' => 'visa.view',
        'admin.finance.' => 'finance.view',
        'admin.hotels.' => 'accommodations.view',
        'admin.partners.' => 'partners.view',
        'admin.reporting.' => 'reporting.view',
        'admin.wordpress.' => 'wordpress.view',
        'admin.settings.' => 'settings.view',
    ],
];
