<?php

/**
 * Catalogue "Pays → Villes" — villes principales par code pays (ISO 3166-1 alpha-2).
 * Utilisé pour l’UI Destination : sélection de villes même sans location WordPress existante.
 * Les noms doivent pouvoir correspondre aux locations WP (normalisation sans accents).
 */
return [
    'MA' => ['Casablanca', 'Rabat', 'Marrakech', 'Fès', 'Tanger', 'Agadir', 'Oujda', 'Meknès', 'Kénitra', 'Tétouan', 'Safi', 'Khouribga', 'Laâyoune', 'Mohammedia', 'El Jadida', 'Béni Mellal', 'Nador', 'Taza', 'Khemisset', 'Settat', 'Larache', 'Ksar El Kébir', 'Guelmim', 'Errachidia', 'Essaouira', 'Azrou', 'Ifrane', 'Chefchaouen', 'Asilah', 'Dakhla', 'Ouarzazate', 'Merzouga'],
    'FR' => ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Nantes', 'Montpellier', 'Strasbourg', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Saint-Étienne', 'Le Havre', 'Toulon', 'Grenoble', 'Dijon', 'Angers', 'Nîmes', 'Villeurbanne', 'Clermont-Ferrand', 'Le Mans', 'Aix-en-Provence', 'Brest', 'Tours', 'Amiens', 'Limoges', 'Annecy', 'Perpignan', 'Béziers', 'Metz', 'Orléans', 'Rouen', 'Mulhouse', 'Caen', 'Nancy', 'Argenteuil', 'Saint-Denis', 'Cannes', 'Avignon'],
    'ES' => ['Madrid', 'Barcelone', 'Valence', 'Séville', 'Saragosse', 'Malaga', 'Murcie', 'Palma de Majorque', 'Las Palmas', 'Bilbao', 'Alicante', 'Cordoue', 'Valladolid', 'Vigo', 'Gijón', 'L\'Hospitalet', 'Vitoria-Gasteiz', 'Grenade', 'Elche', 'Oviedo', 'Badalona', 'Cartagena', 'Sabadell', 'Santiago de Compostela', 'Santander', 'Pampelune', 'Castellón de la Plana', 'Fuenlabrada', 'León', 'Tolède', 'Tarragone', 'Salamanque', 'Cáceres', 'Burgos', 'Cadix', 'Albacete', 'Lérida', 'Logroño', 'Almería', 'Saint-Sébastien'],
    'US' => ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte', 'San Francisco', 'Indianapolis', 'Seattle', 'Denver', 'Boston', 'Nashville', 'Detroit', 'Portland', 'Las Vegas', 'Memphis', 'Louisville', 'Baltimore', 'Milwaukee', 'Albuquerque', 'Tucson', 'Fresno', 'Mesa', 'Sacramento', 'Atlanta', 'Kansas City', 'Miami', 'Raleigh', 'Omaha', 'Cleveland', 'Virginia Beach', 'Oakland'],
    'GB' => ['Londres', 'Birmingham', 'Manchester', 'Leeds', 'Glasgow', 'Southampton', 'Liverpool', 'Newcastle', 'Nottingham', 'Sheffield', 'Bristol', 'Belfast', 'Leicester', 'Edinburgh', 'Cardiff', 'Coventry', 'Hull', 'Bradford', 'Stoke-on-Trent', 'Wolverhampton', 'Derby', 'Southampton', 'Plymouth', 'Reading', 'Northampton', 'Luton', 'Aberdeen', 'Portsmouth', 'Swansea', 'Bournemouth', 'Oxford', 'Cambridge', 'York', 'Bath', 'Canterbury', 'Inverness', 'Brighton', 'Exeter'],
    'IT' => ['Rome', 'Milan', 'Naples', 'Turin', 'Palerme', 'Gênes', 'Bologne', 'Florence', 'Venise', 'Vérone', 'Messine', 'Padoue', 'Trieste', 'Brescia', 'Taranto', 'Prato', 'Modène', 'Reggio de Calabre', 'Reggio d\'Émilie', 'Parme', 'Livourne', 'Cagliari', 'Foggia', 'Ravenne', 'Ferrara', 'Rimini', 'Syracuse', 'Sassari', 'Latina', 'Bergame', 'Vicence', 'Trente', 'Bolzano', 'Pise', 'Sienne', 'Urbino', 'Pérouse', 'Assise'],
    'DE' => ['Berlin', 'Hambourg', 'Munich', 'Cologne', 'Francfort', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig', 'Bréme', 'Dresde', 'Hanovre', 'Nuremberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Münster', 'Karlsruhe', 'Mannheim', 'Augsbourg', 'Wiesbaden', 'Mönchengladbach', 'Brunswick', 'Chemnitz', 'Aix-la-Chapelle', 'Halle', 'Magdebourg', 'Fribourg-en-Brisgau', 'Krefeld', 'Lübeck', 'Oberhausen', 'Erfurt', 'Hagen', 'Rostock', 'Kassel', 'Hamm', 'Mayence'],
    'PT' => ['Lisbonne', 'Porto', 'Amadora', 'Braga', 'Coimbra', 'Funchal', 'Setúbal', 'Almada', 'Agualva-Cacém', 'Queluz', 'Faro', 'Vila Nova de Gaia', 'Barreiro', 'Aveiro', 'Gondomar', 'Guimarães', 'Oeiras', 'Matosinhos', 'Amora', 'Leiria', 'Ponta Delgada', 'Évora', 'Famalicão', 'Cascais', 'Almada', 'Figueira da Foz', 'Sintra', 'Santarem', 'Viseu', 'Fafe'],
    'TN' => ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Gabès', 'Ariana', 'Gafsa', 'Monastir', 'Béja', 'Kasserine', 'Médenine', 'Nabeul', 'Ben Arous', 'Siliana', 'Mahdia', 'Sidi Bouzid', 'Zaghouan', 'Kébili', 'Jendouba', 'Kef', 'Tozeur', 'Tataouine', 'Manouba'],
    'EG' => ['Le Caire', 'Alexandrie', 'Gizeh', 'Chubra al-Khayma', 'Port-Saïd', 'Suez', 'Louxor', 'Assouan', 'Mansourah', 'Tanta', 'Asyut', 'Ismaïlia', 'Fayoum', 'Zagazig', 'Hurghada', 'Damanhur', 'Minya', 'Beni Suef', 'Qena', 'Sohag', 'Charm el-Cheikh', 'Marsa Alam'],
    'TR' => ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Konya', 'Gaziantep', 'Mersin', 'Diyarbakır', 'Kayseri', 'Eskişehir', 'Şanlıurfa', 'Malatya', 'Kahramanmaraş', 'Van', 'Samsun', 'Denizli', 'Trabzon', 'Sivas', 'Batman', 'Elâzığ', 'Erzurum', 'Muğla', 'Bodrum', 'Marmaris', 'Fethiye', 'Pamukkale'],
    'CN' => ['Pékin', 'Shanghai', 'Canton', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xi\'an', 'Nankin', 'Tianjin', 'Suzhou', 'Zhengzhou', 'Chongqing', 'Dongguan', 'Dalian', 'Qingdao', 'Shenyang', 'Harbin', 'Jinan', 'Kunming', 'Changsha', 'Hefei', 'Fuzhou', 'Xiamen', 'Ningbo', 'Wuxi', 'Nantong', 'Zhongshan', 'Foshan', 'Zhuhai'],
    'JP' => ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Kobe', 'Kyoto', 'Fukuoka', 'Kawasaki', 'Saitama', 'Hiroshima', 'Sendai', 'Kitakyushu', 'Chiba', 'Sakai', 'Niigata', 'Hamamatsu', 'Kumamoto', 'Okayama', 'Shizuoka', 'Matsuyama', 'Kagoshima', 'Nara', 'Nagasaki', 'Kanazawa', 'Hakodate', 'Okinawa'],
    'IN' => ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Patna', 'Vadodara', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar'],
    'AE' => ['Dubaï', 'Abou Dhabi', 'Charjah', 'Al Ain', 'Ajman', 'Ras el Khaïmah', 'Fujairah', 'Oum al Qaïwaïn'],
    'SA' => ['Riyad', 'Jeddah', 'La Mecque', 'Médine', 'Dammam', 'Taïf', 'Tabuk', 'Abha', 'Jizan', 'Najran', 'Al Bahah', 'Yanbu', 'Al Khobar', 'Dhahran'],
    'TH' => ['Bangkok', 'Chiang Mai', 'Hat Yai', 'Nakhon Ratchasima', 'Udon Thani', 'Pattaya', 'Phuket', 'Khon Kaen', 'Surat Thani', 'Nakhon Si Thammarat', 'Chiang Rai', 'Krabi', 'Koh Samui', 'Ayutthaya', 'Hua Hin'],
    'VN' => ['Hô Chi Minh-Ville', 'Hanoï', 'Da Nang', 'Haïphong', 'Cần Thơ', 'Biên Hòa', 'Nha Trang', 'Huế', 'Vũng Tàu', 'Đà Lạt', 'Nam Định', 'Quy Nhơn', 'Hải Dương', 'Thanh Hóa', 'Pleiku'],
    'ID' => ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Palembang', 'Makassar', 'Batam', 'Pekanbaru', 'Bogor', 'Denpasar', 'Yogyakarta', 'Malang', 'Balikpapan', 'Manado', 'Banjarmasin', 'Pontianak', 'Cirebon', 'Samarinda', 'Mataram'],
    'MY' => ['Kuala Lumpur', 'George Town', 'Ipoh', 'Johor Bahru', 'Petaling Jaya', 'Shah Alam', 'Malacca', 'Kuching', 'Kota Kinabalu', 'Kota Bharu', 'Kuantan', 'Kangar', 'Alor Setar', 'Kota Melaka'],
    'AU' => ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adélaïde', 'Gold Coast', 'Newcastle', 'Canberra', 'Wollongong', 'Hobart', 'Geelong', 'Townsville', 'Cairns', 'Darwin', 'Launceston', 'Alice Springs'],
    'CA' => ['Toronto', 'Montréal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Québec', 'Hamilton', 'Kitchener', 'London', 'Victoria', 'Halifax', 'Oshawa', 'Windsor', 'Saskatoon', 'Regina', 'Sherbrooke', 'Barrie', 'Kelowna'],
    'BR' => ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belém', 'Goiânia', 'Guarulhos', 'Campinas', 'São Luís', 'São Gonçalo', 'Maceió', 'Duque de Caxias', 'Natal', 'Teresina'],
    'MX' => ['Mexico', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Zapopan', 'Mérida', 'Cancún', 'Tulum', 'Playa del Carmen', 'Oaxaca', 'San Miguel de Allende', 'Guanajuato', 'Querétaro', 'Morelia', 'Acapulco', 'Veracruz', 'Tampico'],
    'AR' => ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'San Miguel de Tucumán', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan', 'Resistencia', 'Neuquén', 'Corrientes', 'Posadas', 'San Salvador de Jujuy', 'Bahía Blanca', 'Paraná', 'Ushuaia', 'Bariloche', 'Iguazú'],
    'ZA' => ['Johannesburg', 'Le Cap', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Pietermaritzburg', 'Nelspruit', 'Kimberley', 'Polokwane', 'Stellenbosch', 'Francfort', 'George', 'Knysna'],
    'KE' => ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi', 'Kitale', 'Garissa', 'Kakamega', 'Nyeri', 'Lamu', 'Nanyuki', 'Meru'],
    'RU' => ['Moscou', 'Saint-Pétersbourg', 'Novossibirsk', 'Iekaterinbourg', 'Kazan', 'Nijni Novgorod', 'Tcheliabinsk', 'Samara', 'Rostov-sur-le-Don', 'Oufa', 'Krasnoïarsk', 'Voronej', 'Perm', 'Volgograd', 'Sotchi', 'Krasnodar', 'Saratov', 'Tioumen', 'Tolyatti', 'Irkoutsk'],
    'PL' => ['Varsovie', 'Cracovie', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice', 'Białystok', 'Gdynia', 'Częstochowa', 'Radom', 'Sosnowiec', 'Toruń', 'Kielce', 'Gliwice', 'Zabrze', 'Olsztyn'],
    'NL' => ['Amsterdam', 'Rotterdam', 'La Haye', 'Utrecht', 'Eindhoven', 'Groningue', 'Tilburg', 'Almere', 'Breda', 'Nimègue', 'Enschede', 'Haarlem', 'Arnhem', 'Zaanstad', 'Amersfoort', 'Apeldoorn', 'Leyde', 'Dordrecht', 'Maastricht', 'Delft'],
    'BE' => ['Bruxelles', 'Anvers', 'Gand', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Louvain', 'Mons', 'Malines', 'Aalst', 'Hasselt', 'La Louvière', 'Tournai', 'Genk', 'Seraing', 'Verviers', 'Mouscron', 'Saint-Nicolas', 'Ostende'],
    'CH' => ['Zurich', 'Genève', 'Bâle', 'Berne', 'Lausanne', 'Winterthour', 'Saint-Gall', 'Lucerne', 'Lugano', 'Biel/Bienne', 'Thoune', 'Schaffhouse', 'Fribourg', 'Chur', 'Neuchâtel', 'Sion', 'Soleure', 'Baden', 'Locarno', 'Interlaken'],
    'AT' => ['Vienne', 'Graz', 'Linz', 'Salzbourg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten', 'Dornbirn', 'Wiener Neustadt', 'Feldkirch', 'Bregenz', 'Kitzbühel', 'Hallstatt'],
    'GR' => ['Athènes', 'Thessalonique', 'Patras', 'Héraklion', 'Larissa', 'Volos', 'Rhodes', 'Ioannina', 'Chalcis', 'Agrinio', 'Kavala', 'Corfou', 'Mykonos', 'Santorin', 'Delphes', 'Olympie'],
    'CZ' => ['Prague', 'Brno', 'Ostrava', 'Pilsen', 'Liberec', 'Olomouc', 'České Budějovice', 'Hradec Králové', 'Ústí nad Labem', 'Pardubice', 'Karlovy Vary', 'Kutná Hora', 'Český Krumlov', 'Telč'],
    'HU' => ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár', 'Szombathely', 'Eger', 'Sopron', 'Veszprém', 'Pannonhalma'],
    'RO' => ['Bucarest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea', 'Brăila', 'Arad', 'Pitești', 'Sibiu', 'Bacău', 'Târgu Mureș', 'Baia Mare', 'Buzău', 'Satu Mare', 'Sighișoara'],
    'DZ' => ['Alger', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Sétif', 'Sidi Bel Abbès', 'Biskra', 'Tébessa', 'Tlemcen', 'Béjaïa', 'Mostaganem', 'Tizi Ouzou', 'Béchar', 'Tindouf', 'Ghardaïa', 'Ouargla', 'Jijel', 'Médéa'],
    'SN' => ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Kaolack', 'Mbour', 'Ziguinchor', 'Saint-Louis', 'Diourbel', 'Louga', 'Tambacounda', 'Kolda', 'Matam', 'Fatick'],
];
